services:

  web:
    container_name: web_app_container
    image: drorganvidez/uvlhub:latest
    env_file:
      - ../.env
    ports:
      - "5000:5000"
    depends_on:
      - db
    build:
      context: ../
      dockerfile: docker/images/Dockerfile.webhook
    restart: always
    volumes:
      - ./entrypoints/production_entrypoint.sh:/app/entrypoint.sh
      - ../scripts:/app/scripts
      - ../migrations:/app/migrations
      - ../uploads:/app/uploads
      - ../:/app
      - /var/run/docker.sock:/var/run/docker.sock
    command: [ "sh", "-c", "sh /app/entrypoint.sh" ]

  db:
    container_name: mariadb_container
    env_file:
      - ../.env
    image: mariadb:latest
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql

networks:
  default:
    name: caddy_net
    external: true


volumes:
  db_data:
