"""Create fakenodo table

Revision ID: 24dbfd49dec3
Revises: 001
Create Date: 2024-11-13 12:25:27.583555

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '24dbfd49dec3'
down_revision = '001'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        'deposition',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('dep_metadata', sa.JSON(), nullable=False),
        sa.Column('status', sa.String(length=50), nullable=False),
        sa.Column('doi', sa.String(length=250), nullable=True),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('doi')
    )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('depositions')
    # ### end Alembic commands ###
